### ISSUE TITLE
Update while typing

### ISSUE THREAD

**Issue by mholt** [keremciu/font-bundles#4]
This is awesome, so thank you for making the plugin!

It would be fantastic for both grid and name insert, the list of icons would be filtered while you're typing; I especially have a hard time finding icons by name, so showing the filtered results while typing would be very helpful.

**Comment by keremciu** [comment]
@mholt so thanks, I am happy to hear them from you

I'd like to update this plugin with invision labs but invision labs did not response to my request. I'm waiting their response but maybe I can find a another way to add new filterable, searchable view because cocoascript is not a good way to build custom views :/
